export const defaultTheme = {
  colors: {
    primary: "#2DC84D",
    secondary: "#f26c38",
    background: "#FFFFFF",
    backgroundMenu: "#FFFF",
    borderButtonHeader: "#E3E3E3",
    backgroundFooter: "#FFFFFF",
    gradient: "linear-gradient(225deg, #040D1E 0%, #2DC84D 100%);",
    success: "#14C38E",
    error: "#d45d5d",
    text: "#1A1A1A",
    text_secondary: "#6F767E",
    input: "#F5F7F5",
    tableThead: "#f7f9fa",
    checkbox: "#040D1E",
    homeBackground: "#6F767E",
    underline: "#707070AD",
    backgroundContainer: "#FFFFFF",
    primaryTextTable: "#040D1E",
    stripe: "#eaeaea",
  },
  textSizes: {
    "title-title-xg": "32px",
    "title-title-g": "28px",
    "title-title-xl": "24px",
    "title-title-l": "20px",
    "title-title-xm": "18px",
    "title-title-m": "16px",
    "title-title-s": "14px",
    "title-title-xs": "12px",
    "components-button-g": "22px",
    "components-button-m": "20px",
    "components-button-s": "16px",
  },
  fonts: {
    regular: "400",
    medium: "500",
    semiBold: "600",
  },
};
